pessoa = {
    10: {
        "nome": "Luis Felipe Pereira",
        "idade": 24,
        "CPF": 4545121545121,
        "endereco": "Rua Cruzeiro do sul",
        "bairro": "Cento e vinte",
        "cidade": "Sanatana de Parnaiba",
    },
    20: {
        "nome": "Herminio Pereira",
        "idade": 55,
        "CPF": 234121545121,
        "endereco": "Rua Cruzeiro do sul 201",
        "bairro": "Cento e vinte",
        "cidade": "Sanatana de Parnaiba",
    },
    30: {
        "nome": "Givaneide Maria Pereira",
        "idade": 50,
        "CPF": 45451245451,
        "endereco": "Rua Cruzeiro do sul 201",
        "bairro": "Cento e vinte",
        "cidade": "Sanatana de Parnaiba",
    },
    40: {
        "nome": "Denilson da Silva Pereira",
        "idade": 22,
        "CPF": 4545123423121,
        "endereco": "Rua Cruzeiro do sul 201 ",
        "bairro": "Cento e vinte",
        "cidade": "Sanatana de Parnaiba",
    },
    70: {
        "nome": "Matheus Silva",
        "idade": 45,
        "CPF": 4545121545121,
        "endereco": "Rua Pedro colasso 72",
        "bairro": "Cento e vinte",
        "cidade": "Sanatana de Parnaiba",
    },
    60: {
        "nome": "Giselle Maria",
        "idade": 24,
        "CPF": 45455454225,
        "endereco": "Rua Astronauta 98",
        "bairro": "Cento e vinte",
        "cidade": "Sanatana de Parnaiba",
    },
    50: {
        "nome": "Carlos Alberto",
        "idade": 30,
        "CPF": 7890123456789,
        "endereco": "Rua das Flores 123",
        "bairro": "Jardim Primavera",
        "cidade": "São Paulo",
    },
    80: {
        "nome": "Aline Oliveira",
        "idade": 28,
        "CPF": 9876543210123,
        "endereco": "Avenida Central 456",
        "bairro": "Centro",
        "cidade": "Rio de Janeiro",
    },
    90: {
        "nome": "Ricardo Santos",
        "idade": 35,
        "CPF": 1230987654321,
        "endereco": "Rua do Comércio 789",
        "bairro": "Centro",
        "cidade": "Salvador",
    },
    100: {
        "nome": "Juliana Lima",
        "idade": 26,
        "CPF": 5678901234567,
        "endereco": "Avenida da Paz 321",
        "bairro": "Jardim das Flores",
        "cidade": "Brasília",
    },
    110: {
        "nome": "Lucas Souza",
        "idade": 32,
        "CPF": 3456789012345,
        "endereco": "Rua da Liberdade 654",
        "bairro": "Liberdade",
        "cidade": "São Paulo",
    },
    120: {
        "nome": "Fernanda Santos",
        "idade": 29,
        "CPF": 5678901234567,
        "endereco": "Avenida Principal 987",
        "bairro": "Centro",
        "cidade": "Belo Horizonte",
    },
    130: {
        "nome": "Roberto Oliveira",
        "idade": 40,
        "CPF": 4567890123456,
        "endereco": "Rua das Árvores 741",
        "bairro": "Jardim Botânico",
        "cidade": "Curitiba",
    },
    140: {
        "nome": "Camila Silva",
        "idade": 27,
        "CPF": 7890123456789,
        "endereco": "Avenida dos Sonhos 852",
        "bairro": "Vila Feliz",
        "cidade": "Porto Alegre",
    },
    150: {
        "nome": "Pedro Costa",
        "idade": 38,
        "CPF": 5678901234567,
        "endereco": "Rua das Montanhas 369",
        "bairro": "Vila Nova",
        "cidade": "Fortaleza",
    },
    160: {
        "nome": "Mariana Oliveira",
        "idade": 31,
        "CPF": 2345678901234,
        "endereco": "Avenida dos Ventos 147",
        "bairro": "Jardim do Mar",
        "cidade": "Recife",
    },
}
for chave in pessoa:
    print(pessoa[chave])

